Controllers/CandidateController.cs
using AT2_CS_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Metrics;
using System.Linq;

namespace AT2_CS_MVC.Controllers
{
    public class CandidateController : Controller
    {
        private readonly ApplicantDbContext _db;
        public CandidateController(ApplicantDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            
            return View(GetQualificationDetail());
        }

        [HttpGet]
        public IActionResult add()
        {
            Display Ap_list = new Display();
            Ap_list.dob = DateTime.Now;
            
            FillArrayQ(Ap_list);
            return View(Ap_list);

        }

        [HttpPost]
        public IActionResult add(Display Ap_list)
        {
            Applicant ap = new Applicant();
            ap.name = Ap_list.name;
            ap.dob = Ap_list.dob;
            //find the QId by Qname 
            //var quaData = _db.QualificationsDB.FirstOrDefault(q => q.Qname == Ap_list.Qname);

                //if (quaData != null)
                //{
                //    ap.QId = quaData.QId; // Assign QId only if a match is found
                //}
           
            if (int.TryParse(Ap_list.Qname, out int qId))
            {
                ap.QId = qId;
            }
            else
            {
                ap.QId = 0;
            }
            ap.gpa = Ap_list.gpa;
            ap.university = Ap_list.university;
            try
            {
                if (ModelState.IsValid)
                {
                    _db.ApplicantsDB.Add(ap);
                    _db.SaveChanges();
                }
                else{
                    FillArrayQ(Ap_list);
                    return View(Ap_list);
                }

            }
            catch (Exception ex)
            {

            }

            return RedirectToAction("index");

        }

        [HttpGet]
        public IActionResult delete(int Id)
        {

            Applicant editData = _db.ApplicantsDB.Find(Id);
            _db.ApplicantsDB.Remove(editData);
            _db.SaveChanges();

            return RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult edit(int Id)
        {
            Applicant editData = _db.ApplicantsDB.Find(Id);
            Display ds = new Display();
            ds.AId = editData.AId;
            ds.name = editData.name;
            ds.dob = editData.dob;
            ds.QId = editData.QId;
            ds.gpa = editData.gpa;
            ds.university = editData.university;
            ds.ListQualification = _db.QualificationsDB
                                    .Select(q => new SelectListItem
                                    {
                                        Value = q.QId.ToString(),
                                        Text = q.Qname,
                                        Selected = q.QId == editData.QId // Ensure previous value is selected
                                    })
                                .ToList();
            //FillArrayQ(ds);
            return View(ds);
        }

        [HttpPost]
        public IActionResult edit(Display editData)
        {

            Applicant ap = _db.ApplicantsDB.Find(editData.AId);
            ap.name = editData.name;
            ap.dob = editData.dob;
            //find the QId by Qname 
            //var quaData = _db.QualificationsDB.FirstOrDefault(q => q.Qname == editData.Qname);
            // Convert QId string back to integer before saving
            if (int.TryParse(editData.Qname, out int qId))
            {
                ap.QId = qId;
            }
            else
            {
                ap.QId = 0; // Or any default value that makes sense
            }
            //ap.QId = quaData.QId;
            ap.gpa = editData.gpa;
            ap.university = editData.university;



            if (ModelState.IsValid && editData.Qname != null)
            {
                _db.ApplicantsDB.Update(ap);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                FillArrayQ(editData);
                return View(editData);
            }

        }
        private List<Display> GetQualificationDetail()
        {
            var Display_list = (from ap in _db.ApplicantsDB
                                join qua in _db.QualificationsDB
                                on ap.QId equals qua.QId
                                orderby ap.gpa descending  // Ordering by GPA in descending order
                                select new Display
                                {
                                    AId = ap.AId,
                                    name = ap.name,
                                    dob = ap.dob,
                                    QId = ap.QId,
                                    gpa = ap.gpa,
                                    university = ap.university,
                                    Qname = qua.Qname
                                }).ToList();

            return Display_list;
          
        }
        
        private void FillArrayQ(Display pref)
        {

            var qua = _db.QualificationsDB.ToList();

            //ds.ListQualification = _db.QualificationsDB
            //            .Select(q => new SelectListItem
            //            {
            //                Value = q.QId.ToString(),
            //                Text = q.Qname,
            //                Selected = q.QId == editData.QId // Ensure previous value is selected
            //            })
            //        .ToList();

            foreach (var item in qua)
            {
                pref.ListQualification.Add(new SelectListItem { Value = item.QId.ToString(), Text = item.Qname, });
            }

           
            //pref.ListQualification.Add(new SelectListItem { Text = "Master of Artificial Intelligence", Value = "Master of Artificial Intelligence" });
            //pref.ListQualification.Add(new SelectListItem { Text = "Master of Information Technology", Value = "Master of Information Technology" });
            //pref.ListQualification.Add(new SelectListItem { Text = "Master of Science(Statistics)", Value = "Master of Science (Statistics)" });

        }
     

    }
}

Views/Candidate/Add.cshtml
@model AT2_CS_MVC.Models.Display

<fieldset>

    @using (Html.BeginForm())
    {

        @Html.ValidationSummary()
        //new Post { Id = 1, newsContents = "Russian - USA", Title = " XXXX 1", publishedBy = "Jose", publishedOn = Convert.ToDateTime("2024-12-01"), publishedContry = "Thailand" },
        <table class="table table-striped">
            <tr><td>@Html.LabelFor(m => m.name)</td> <td>@Html.EditorFor(m => m.name)@Html.ValidationMessageFor(m => m.name)</td></tr>
            <tr><td>@Html.LabelFor(m => m.dob)</td> <td>@Html.EditorFor(m => m.dob)</td></tr>
            <tr><td>@Html.LabelFor(m => m.gpa)</td> <td> @Html.TextBoxFor(m => m.gpa, new {type = "number", step = "0.01", min = "3.0", max = "4.0" })@Html.ValidationMessageFor(m => m.gpa)</td></tr>
           
            <tr><td>@Html.LabelFor(m => m.university)</td> <td>@Html.EditorFor(m => m.university)@Html.ValidationMessageFor(m => m.university)</td></tr>
            <tr>
                <td>@Html.LabelFor(m => m.Qname)</td>
                <td>@Html.DropDownListFor(m => m.Qname, Model.ListQualification, "Select Qualification", new { IDataTokensMetadata = "ddID" })@Html.ValidationMessageFor(m => m.Qname)</td>
            </tr>

            <tr><td></td><td><button type="submit">ADD</button></td></tr>
        </table>
    }


</fieldset>

Views/Candidate/Edit.cshtml
@model AT2_CS_MVC.Models.Display

<fieldset>

    @using (Html.BeginForm())
    {

        @Html.ValidationSummary()
        //new Post { Id = 1, newsContents = "Russian - USA", Title = " XXXX 1", publishedBy = "Jose", publishedOn = Convert.ToDateTime("2024-12-01"), publishedContry = "Thailand" },
        <table class="table table-striped">
            <tr><td>@Html.LabelFor(m => m.name)</td> <td>@Html.EditorFor(m => m.name)@Html.ValidationMessageFor(m => m.name)</td></tr>
            <tr><td>@Html.LabelFor(m => m.dob)</td> <td>@Html.EditorFor(m => m.dob)</td></tr>
            <tr><td>@Html.LabelFor(m => m.gpa)</td> <td>@Html.EditorFor(m => m.gpa)@Html.ValidationMessageFor(m => m.gpa)</td></tr>
            <tr><td>@Html.LabelFor(m => m.university)</td> <td>@Html.EditorFor(m => m.university)</td></tr>
            <tr>
                <td>@Html.LabelFor(m => m.Qname)</td>
                <td>@Html.DropDownListFor(m => m.Qname, Model.ListQualification, "Select Qualification", new { IDataTokensMetadata = "ddID" })@Html.ValidationMessageFor(m => m.Qname)</td>
            </tr>
            @Html.HiddenFor(m => m.AId)
            <tr><td></td><td><button type="submit">Update</button></td></tr>
        </table>
    }


</fieldset>

Views/Candidate/Index.cshtml
@model IEnumerable<AT2_CS_MVC.Models.Display>
@{
    ViewData["Title"] = "Candidate Home Index";
}


<h2 class="h1 accordion-header"> MIT University - Candidate Management </h2>

<div class="mb-4">
    <button class="btn btn-dark">@Html.ActionLink("Add New Candidate", "Add", "Candidate", null, new { style = "text-decoration: none; color:white;" }) </button>
    <br>
    <br>
    <input class="text text-black-50"type="text" id="searchInput" placeholder="Search Name or Univesity" onkeyup="filterTable()" />
    @* <button class="btnLink btn btn-dark">@Html.ActionLink("Back to Home", "Index", "Home") </button> *@
</div>

<table class="table table-responsive" id="dataTable">
    <tr >
        <th onclick="sortTable(0)">@Html.DisplayNameFor(m => m.name) ⇅</th>
        <th onclick="sortTable(1)">@Html.DisplayNameFor(m => m.dob) ⇅</th>
        <th onclick="sortTable(2)">@Html.DisplayNameFor(m => m.gpa) ⇅</th>
        <th onclick="sortTable(3)">@Html.DisplayNameFor(m => m.university) ⇅</th>
        <th onclick="sortTable(4)">@Html.DisplayNameFor(m => m.Qname) ⇅</th>
    </tr>

    @foreach (var data in Model)
    {

        <tr>
            <td>@data.name</td>
            <td>@Convert.ToDateTime(data.dob).ToString("dd-MM-yyyy")</td>
            <td>@data.gpa</td>
            <td>@data.university</td>
            <td>@data.Qname</td>
            <td>@Html.ActionLink("EDIT", "edit", "Candidate", new { @id = data.AId })</td>
            <td>@Html.ActionLink("DELETE", "delete", "Candidate", new { @id = data.AId }, new { onclick = "return confirm('Click ok to del');" })</td>
        </tr>
    }

</table>

<script src="~/js/index_candidate.js" asp-append-version="true"></script>